### ISSUE TITLE
Problem with storing different versions

### ISSUE THREAD

**Issue by asartalo** [diogob/carrierwave-postgresql#10]
This is just a question. The solution is not obvious to me. I can't seem to store different versions on the db. This is probably because I'm using only one column to store the oid. How does one go about creating and storing different versions? My code is like this:

``` ruby
class ImageUploader < CarrierWave::Uploader::Base

  include CarrierWave::RMagick

  # Choose what kind of storage to use for this uploader:
  storage :postgresql_lo

  process resize_to_fit: [960, 960]

  version :thumb do
    process resize_to_fill: [200,200]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

end
```

And my model looks like this

``` ruby
class Foo
  mount_uploader :image, ImageUploader
end
```

This only stores the _thumb_ version which is probably the last version specified. Thanks!

**Comment by nfedyashev** [comment]
@diogob thanks for posting workaround!

**Comment by GUI** [comment]
If anyone else is interested in version support, I've published a different gem, [carrierwave-postgresql-table](https://github.com/GUI/carrierwave-postgresql-table) that provides version support by tackling the storage in a slightly different way. It requires the use of an extra table to store metadata about all the file uploads, but the underlying object storage is the same (using postgres large objects). Due to the differences in how it stores data, it's not compatible with carrierwave-postgresql, but I thought I'd mention it in case others looking for version support find it useful.

And big thanks to @diogob for providing carrierwave-postgresql that I was able to use as reference. I didn't submit my gem as a pull request due to it's backwards incompatible nature, but if you are interested in the changes, let me know, and I can try to see how far the code has diverged.
